"Filed out from Dolphin Smalltalk"!

GRAbstractSequenceableCollectionTest subclass: #GRArrayTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRArrayTest guid: (GUID fromString: '{4f94d7ef-2f05-4388-a46c-7aa306c6ad40}')!

GRArrayTest comment: ''!

!GRArrayTest categoriesForClass!Unclassified! !

!GRArrayTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ Array!

isExtensible	^ false!

isHomogeneous	^ false!

isInitializable	^ true!

isSequenced	^ true!

isUnique	^ false! !

!GRArrayTest categoriesForMethods!
allowsDuplicateValues!configuration!public! !
collectionClass!configuration!public! !
isExtensible!public!testing/ansi! !
isHomogeneous!public!testing! !
isInitializable!public!testing/ansi! !
isSequenced!public!testing/ansi! !
isUnique!public!testing! !
!

