"Filed out from Dolphin Smalltalk"!

GRCollectionTest subclass: #GRBagTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRBagTest guid: (GUID fromString: '{d0f1a789-ddc0-4c33-9894-16d041e064ff}')!

GRBagTest comment: ''!

!GRBagTest categoriesForClass!Unclassified! !

!GRBagTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ Bag!

isExtensible	^ true!

isInitializable	^ true! !

!GRBagTest categoriesForMethods!
allowsDuplicateValues!configuration!public! !
collectionClass!configuration!public! !
isExtensible!public!testing/ansi! !
isInitializable!public!testing/ansi! !
!

