"Filed out from Dolphin Smalltalk 7"!

GRCollectionTest subclass: #GRBagTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRBagTest guid: (GUID fromString: '{805bb46e-f756-42b4-b788-2d7d0a6ac983}')!
GRBagTest comment: ''!
!GRBagTest categoriesForClass!Grease-Tests-Core! !
!GRBagTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ Bag!

isExtensible	^ true!

isInitializable	^ true! !
!GRBagTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GRBagTest categoriesFor: #collectionClass!configuration!public! !
!GRBagTest categoriesFor: #isExtensible!public!testing/ansi! !
!GRBagTest categoriesFor: #isInitializable!public!testing/ansi! !

