"Filed out from Dolphin Smalltalk 7"!

GRDelegatingStream subclass: #GRCodecStream
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRCodecStream guid: (GUID fromString: '{1445f22a-a942-4cbe-a8b3-d71a84d7eb73}')!
GRCodecStream comment: 'GRObject subclass: #GRInflector	instanceVariableNames: ''''	classVariableNames: ''InflectionRules Uninflected''	package: ''Grease-Core-Text'''!
!GRCodecStream categoriesForClass!Grease-Core-Text! !
