"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #GRErrorStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRErrorStub guid: (GUID fromString: '{1bf2291c-6a6b-454d-aaf2-de95d5963b9e}')!
GRErrorStub comment: ''!
!GRErrorStub categoriesForClass!Grease-Tests-Core! !
!GRErrorStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRErrorStub categoriesFor: #foo!accessing!public! !
!GRErrorStub categoriesFor: #initialize!initialization!public! !

