"Filed out from Dolphin Smalltalk 7"!

Error subclass: #GRError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRError guid: (GUID fromString: '{d1c06336-a306-4b29-a2ab-382bce08b0e3}')!
GRError comment: 'Notification subclass: #GRNotification	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Grease-Core-Exceptions'''!
!GRError categoriesForClass!Grease-Core-Exceptions! !
