"Filed out from Dolphin Smalltalk"!

GRError subclass: #GRErrorStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRErrorStub guid: (GUID fromString: '{a3e27a8c-bf43-461b-83bb-55ec1754eb2c}')!

GRErrorStub comment: ''!

!GRErrorStub categoriesForClass!Unclassified! !

!GRErrorStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !

!GRErrorStub categoriesForMethods!
foo!accessing!public! !
initialize!initialization!public! !
!

