"Filed out from Dolphin Smalltalk"!

GRError subclass: #GRInvalidUtf8Error
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRInvalidUtf8Error guid: (GUID fromString: '{1719b88d-fd0f-43af-b34c-8553669dfdab}')!

GRInvalidUtf8Error comment: 'A WAInvalidUtf8Error signals that the input is not valid UTF-8.'!

!GRInvalidUtf8Error categoriesForClass!Text! !

