"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #GRInvalidArgumentCount
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRInvalidArgumentCount guid: (GUID fromString: '{8d1b683c-43ce-453f-9225-39e82a5a35d1}')!
GRInvalidArgumentCount comment: 'GRNotification subclass: #GRNotificationBasedDynamicVariable	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Grease-Core-Utilities'''!
!GRInvalidArgumentCount categoriesForClass!Grease-Core-Utilities! !
