"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #GRInvalidUtf8Error
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRInvalidUtf8Error guid: (GUID fromString: '{72bdb433-efca-4bcf-bba4-a48528e074be}')!
GRInvalidUtf8Error comment: 'GRCodec subclass: #GRNullCodec	instanceVariableNames: ''''	classVariableNames: ''''	package: ''Grease-Core-Text'''!
!GRInvalidUtf8Error categoriesForClass!Grease-Core-Text! !
