"Filed out from Dolphin Smalltalk"!

GRError subclass: #GRInvalidArgumentCount
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRInvalidArgumentCount guid: (GUID fromString: '{9a6fac08-4e7d-4442-bf43-3f975fecc23d}')!

GRInvalidArgumentCount comment: 'Signaled whenever a message is sent with the incorrect number of arguments.'!

!GRInvalidArgumentCount categoriesForClass!Utilities! !

