"Filed out from Dolphin Smalltalk 7"!

GRNotification subclass: #GRNotificationStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRNotificationStub guid: (GUID fromString: '{2c41ff4a-3f08-4a76-a786-8a228bb267ef}')!
GRNotificationStub comment: ''!
!GRNotificationStub categoriesForClass!Grease-Tests-Core! !
!GRNotificationStub methodsFor!

defaultAction	^ #returnValue!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRNotificationStub categoriesFor: #defaultAction!accessing!public! !
!GRNotificationStub categoriesFor: #foo!accessing!public! !
!GRNotificationStub categoriesFor: #initialize!initialization!public! !

