"Filed out from Dolphin Smalltalk"!

GRNotification subclass: #GRNotificationStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRNotificationStub guid: (GUID fromString: '{bb8be566-5258-466a-9720-6ee950bae4a2}')!

GRNotificationStub comment: ''!

!GRNotificationStub categoriesForClass!Unclassified! !

!GRNotificationStub methodsFor!

defaultAction	^ #returnValue!

foo	^ foo!

initialize	super initialize.	foo := true! !

!GRNotificationStub categoriesForMethods!
defaultAction!accessing!public! !
foo!accessing!public! !
initialize!initialization!public! !
!

