"Filed out from Dolphin Smalltalk 7"!

Notification subclass: #GRNotification
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRNotification guid: (GUID fromString: '{519dc4db-5d48-48e3-bcdb-03b30863f125}')!
GRNotification comment: 'GRNotification subclass: #GRDeprecatedApiNotification	instanceVariableNames: ''details''	classVariableNames: ''''	package: ''Grease-Core-Exceptions'''!
!GRNotification categoriesForClass!Grease-Core-Exceptions! !
