"Filed out from Dolphin Smalltalk"!

GRObject subclass: #GRObjectStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRObjectStub guid: (GUID fromString: '{1cb10c80-9fb6-4dc9-94c9-21b2809037cf}')!

GRObjectStub comment: ''!

!GRObjectStub categoriesForClass!Unclassified! !

!GRObjectStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !

!GRObjectStub categoriesForMethods!
foo!accessing!public! !
initialize!initialization!public! !
!

