"Filed out from Dolphin Smalltalk 7"!

GRObject subclass: #GRObjectStub
	instanceVariableNames: 'foo'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRObjectStub guid: (GUID fromString: '{5f4c6856-1f08-405b-93e5-42497c5b1a30}')!
GRObjectStub comment: ''!
!GRObjectStub categoriesForClass!Grease-Tests-Core! !
!GRObjectStub methodsFor!

foo	^ foo!

initialize	super initialize.	foo := true! !
!GRObjectStub categoriesFor: #foo!accessing!public! !
!GRObjectStub categoriesFor: #initialize!initialization!public! !

