"Filed out from Dolphin Smalltalk"!

GROrderedMultiMapTest subclass: #GROrderedMultiMap2Test
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GROrderedMultiMap2Test guid: (GUID fromString: '{d83ae703-2b35-4b50-b5e5-116273338af4}')!

GROrderedMultiMap2Test comment: ''!

!GROrderedMultiMap2Test categoriesForClass!Unclassified! !

!GROrderedMultiMap2Test methodsFor!

collectionClass	^ GROrderedMultiMap2! !

!GROrderedMultiMap2Test categoriesForMethods!
collectionClass!configuration!public! !
!

