"Filed out from Dolphin Smalltalk 7"!

GROrderedMultiMapTest subclass: #GROrderedMultiMap2Test
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GROrderedMultiMap2Test guid: (GUID fromString: '{7658744e-1084-4514-858a-2163a6177f93}')!
GROrderedMultiMap2Test comment: ''!
!GROrderedMultiMap2Test categoriesForClass!Grease-Tests-Core! !
!GROrderedMultiMap2Test methodsFor!

collectionClass	^ GROrderedMultiMap2! !
!GROrderedMultiMap2Test categoriesFor: #collectionClass!configuration!public! !

