"Filed out from Dolphin Smalltalk"!

GRAbstractSequenceableCollectionTest subclass: #GROrderedCollectionTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GROrderedCollectionTest guid: (GUID fromString: '{cc1fe251-2139-47c0-866c-4a8a3dde36b1}')!

GROrderedCollectionTest comment: ''!

!GROrderedCollectionTest categoriesForClass!Unclassified! !

!GROrderedCollectionTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ OrderedCollection!

isExtensible	^ true!

isHomogeneous	^ false!

isInitializable	^ true!

isSequenced	^ true!

isUnique	^ false! !

!GROrderedCollectionTest categoriesForMethods!
allowsDuplicateValues!configuration!public! !
collectionClass!configuration!public! !
isExtensible!public!testing/ansi! !
isHomogeneous!public!testing! !
isInitializable!public!testing/ansi! !
isSequenced!public!testing/ansi! !
isUnique!public!testing! !
!

