"Filed out from Dolphin Smalltalk"!

GRDictionaryTest subclass: #GRReducedConflictDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRReducedConflictDictionaryTest guid: (GUID fromString: '{9e6f024c-4307-4188-9ab9-0eaeccb75743}')!

GRReducedConflictDictionaryTest comment: ''!

!GRReducedConflictDictionaryTest categoriesForClass!Unclassified! !

!GRReducedConflictDictionaryTest methodsFor!

collectionClass	^ GRPlatform current reducedConflictDictionary! !

!GRReducedConflictDictionaryTest categoriesForMethods!
collectionClass!configuration!public! !
!

