"Filed out from Dolphin Smalltalk 7"!

GRDictionaryTest subclass: #GRReducedConflictDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRReducedConflictDictionaryTest guid: (GUID fromString: '{82bc201a-b127-4470-8e1f-4fa113ef50c4}')!
GRReducedConflictDictionaryTest comment: ''!
!GRReducedConflictDictionaryTest categoriesForClass!Grease-Tests-Core! !
!GRReducedConflictDictionaryTest methodsFor!

collectionClass	^ GRPlatform current reducedConflictDictionary! !
!GRReducedConflictDictionaryTest categoriesFor: #collectionClass!configuration!public! !

