"Filed out from Dolphin Smalltalk"!

GRCollectionTest subclass: #GRSetTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRSetTest guid: (GUID fromString: '{0cf0a0ff-8cc1-4bf9-9473-7c937241a08a}')!

GRSetTest comment: ''!

!GRSetTest categoriesForClass!Unclassified! !

!GRSetTest methodsFor!

allowsDuplicateValues	^ false!

collectionClass	^ Set!

isExtensible	^ true!

isInitializable	^ true! !

!GRSetTest categoriesForMethods!
allowsDuplicateValues!configuration!public! !
collectionClass!configuration!public! !
isExtensible!public!testing/ansi! !
isInitializable!public!testing/ansi! !
!

