"Filed out from Dolphin Smalltalk 7"!

GRCollectionTest subclass: #GRSetTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRSetTest guid: (GUID fromString: '{289f8c3b-310b-45f8-b080-d2e0914f52c3}')!
GRSetTest comment: ''!
!GRSetTest categoriesForClass!Grease-Tests-Core! !
!GRSetTest methodsFor!

allowsDuplicateValues	^ false!

collectionClass	^ Set!

isExtensible	^ true!

isInitializable	^ true! !
!GRSetTest categoriesFor: #allowsDuplicateValues!configuration!public! !
!GRSetTest categoriesFor: #collectionClass!configuration!public! !
!GRSetTest categoriesFor: #isExtensible!public!testing/ansi! !
!GRSetTest categoriesFor: #isInitializable!public!testing/ansi! !

