"Filed out from Dolphin Smalltalk 7"!

GRSmallDictionaryTest subclass: #GRSmallDictionary2Test
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRSmallDictionary2Test guid: (GUID fromString: '{7df78dc1-c626-4a47-83da-22640094f2e2}')!
GRSmallDictionary2Test comment: ''!
!GRSmallDictionary2Test categoriesForClass!Grease-Tests-Core! !
!GRSmallDictionary2Test methodsFor!

collectionClass	^ GRSmallDictionary2! !
!GRSmallDictionary2Test categoriesFor: #collectionClass!configuration!public! !

