"Filed out from Dolphin Smalltalk"!

GRSmallDictionaryTest subclass: #GRSmallDictionary2Test
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRSmallDictionary2Test guid: (GUID fromString: '{e75fc147-2337-495e-b75a-ec2db899192b}')!

GRSmallDictionary2Test comment: ''!

!GRSmallDictionary2Test categoriesForClass!Unclassified! !

!GRSmallDictionary2Test methodsFor!

collectionClass	^ GRSmallDictionary2! !

!GRSmallDictionary2Test categoriesForMethods!
collectionClass!configuration!public! !
!

