"Filed out from Dolphin Smalltalk"!

GRAbstractSequenceableCollectionTest subclass: #GRSortedCollectionTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRSortedCollectionTest guid: (GUID fromString: '{df36bc23-8cb4-473d-b56b-0484c83c6efd}')!

GRSortedCollectionTest comment: ''!

!GRSortedCollectionTest categoriesForClass!Unclassified! !

!GRSortedCollectionTest methodsFor!

allowsDuplicateValues	^ true!

collectionClass	^ SortedCollection!

isExtensible	^ true!

isHomogeneous	^ true!

isInitializable	^ true!

isSequenced	^ false!

isUnique	^ false! !

!GRSortedCollectionTest categoriesForMethods!
allowsDuplicateValues!configuration!public! !
collectionClass!configuration!public! !
isExtensible!public!testing/ansi! !
isHomogeneous!public!testing! !
isInitializable!public!testing/ansi! !
isSequenced!public!testing/ansi! !
isUnique!public!testing! !
!

