"Filed out from Dolphin Smalltalk"!

GRAbstractSequenceableCollectionTest subclass: #GRSymbolTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRSymbolTest guid: (GUID fromString: '{c9c6c819-f102-4e6b-bca6-c5273e987e04}')!

GRSymbolTest comment: ''!

!GRSymbolTest categoriesForClass!Unclassified! !

!GRSymbolTest methodsFor!

allowsDuplicateValues	^ true!

arbitraryCollection	^ #'fadbbc'!

collectionClass	^ Symbol!

duplicateElement	^ $b!

emptyCollection	^ #''!

excludedElement	^ $Q!

includedElement	^ $d!

isExtensible	^ false!

isHomogeneous	^ true!

isInitializable	^ false!

isSequenced	^ false!

isUnique	^ true! !

!GRSymbolTest categoriesForMethods!
allowsDuplicateValues!configuration!public! !
arbitraryCollection!configuration!public! !
collectionClass!configuration!public! !
duplicateElement!configuration!public! !
emptyCollection!configuration!public! !
excludedElement!configuration!public! !
includedElement!configuration!public! !
isExtensible!public!testing/ansi! !
isHomogeneous!public!testing! !
isInitializable!public!testing/ansi! !
isSequenced!public!testing/ansi! !
isUnique!public!testing! !
!

