"Filed out from Dolphin Smalltalk"!

GRNotificationBasedDynamicVariable subclass: #GRTestNotificationBasedDynamicVariable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRTestNotificationBasedDynamicVariable guid: (GUID fromString: '{aa4dbbfc-855b-4047-92b8-fc036e90451a}')!

GRTestNotificationBasedDynamicVariable comment: ''!

!GRTestNotificationBasedDynamicVariable categoriesForClass!Unclassified! !

!GRTestNotificationBasedDynamicVariable class methodsFor!

defaultValue	^ 'default test value'! !

!GRTestNotificationBasedDynamicVariable class categoriesForMethods!
defaultValue!defaults!public! !
!

