"Filed out from Dolphin Smalltalk 7"!

GRNotificationBasedDynamicVariable subclass: #GRTestNotificationBasedDynamicVariable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRTestNotificationBasedDynamicVariable guid: (GUID fromString: '{30013648-a954-4804-9a9c-2aa90cdb48cb}')!
GRTestNotificationBasedDynamicVariable comment: ''!
!GRTestNotificationBasedDynamicVariable categoriesForClass!Grease-Tests-Core! !
!GRTestNotificationBasedDynamicVariable class methodsFor!

defaultValue	^ 'default test value'! !
!GRTestNotificationBasedDynamicVariable class categoriesFor: #defaultValue!defaults!public! !

