"Filed out from Dolphin Smalltalk"!

GRDynamicVariable subclass: #GRTestDynamicVariable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

GRTestDynamicVariable guid: (GUID fromString: '{4c16fbf2-75bd-4bb9-8584-e9ecffdf024c}')!

GRTestDynamicVariable comment: ''!

!GRTestDynamicVariable categoriesForClass!Unclassified! !

!GRTestDynamicVariable class methodsFor!

defaultValue	^ 'default test value'! !

!GRTestDynamicVariable class categoriesForMethods!
defaultValue!defaults!public! !
!

