"Filed out from Dolphin Smalltalk 7"!

GRDynamicVariable subclass: #GRTestDynamicVariable
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GRTestDynamicVariable guid: (GUID fromString: '{8fb724ba-080d-41f1-a2f9-aaf1ad9fdc4b}')!
GRTestDynamicVariable comment: ''!
!GRTestDynamicVariable categoriesForClass!Grease-Tests-Core! !
!GRTestDynamicVariable class methodsFor!

defaultValue	^ 'default test value'! !
!GRTestDynamicVariable class categoriesFor: #defaultValue!defaults!public! !

